<?xml version="1.0" encoding="utf-8"?><Database Name="Week14" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=Week14;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="Week14.Properties.Settings" SettingsPropertyName="Week14ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.pelanggan" Member="pelanggans">
    <Type Name="pelanggan">
      <Column Name="id_pelanggan" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nama_pelanggan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.pemasok" Member="pemasoks">
    <Type Name="pemasok">
      <Column Name="id_pemasok" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nama_pemasok" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>